#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Haruto Higuma
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans1 = 0
ans2 = 0
for line in sys.stdin:
    try:
        ans1 += int(line)
        ans2 -= int(line)    
    except:
        ans1 += float(line)
        ans2 -= float(line)

print(ans1)
print(ans2)

if ans1 < 100:
    print("ans1<100")
elif ans1 > 100:
    print("ans1>100")

if ans2 < 100:
    print("ans2<100")
elif ans2 > 100:
   print("ans2>100")

